# Generated by Django 2.1.1 on 2018-09-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180917_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
